spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easykotlin
    username: admin
    password: MGSnVtE20fuz
# Keep the connection alive if idle for a long time(needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
# Show or not log for each sql query
    show-sql: true
    hibernate:
# Hibernate ddl auto (Create, create-drop, update)
      ddl-auto: update
# Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
# The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
